version: '3.8'

services:
  database:
    image: neo4j:5.15.0
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_server_default__listen__address=0.0.0.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - app-network

  app:
    build: .
    environment:
      - NEO4J_URI=neo4j://database:7687
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - LLM=${LLM}
      - EMBEDDING_MODEL=ollama
      - STREAMLIT_SERVER_PORT=8503
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    ports:
      - "8503:8503"
    depends_on:
      - database
    networks:
      - app-network

volumes:
  neo4j_data:
    driver: local

networks:
  app-network:
    driver: bridge