version: '3'
services:
  bot:
    build: .
    ports:
      - "8503:8503"
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - OLLAMA_BASE_URL=http://ollama:11434
      - LLM=llama3.2:3b
    depends_on:
      - neo4j
      - ollama

  neo4j:
    image: neo4j:5.11.0
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_AUTH=neo4j/password

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/ollama"]
    command: ["serve"]

volumes:
  ollama_data: